name: Test SPell

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Run
      run: |
        sudo apt-get update
        sudo apt-get install -y primesieve
        ./configure
        make
        time ./p833d --initial 10e35.dat $(bc <<< "10^35") 136101521 2>&1 | tee >(grep -vP "(^\d+\.\d+%$)|(^bucket: \[\d+, \d+\)$)" > 1.303481.log)
        ./babysitter.py 2 6
    - uses: actions/upload-artifact@v3
      with:
        name: logs
        path: *.log
